version: '3.7'
services:
  master:
    image: redis
    container_name: redis-master
    restart: always
    command: redis-server --port 6379 --requirepass test@dbuser2020  --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    networks:
      hx_net:
        ipv4_address: 11.11.11.11

  slave1:
    image: redis
    container_name: redis-slave-1
    restart: always
    command: redis-server --slaveof 11.11.11.11 6379 --port 6380  --requirepass test@dbuser2020 --masterauth test@dbuser2020  --appendonly yes
    ports:
      - 6380:6380
    volumes:
      - ./data:/data
    networks:
      hx_net:
        ipv4_address: 11.11.11.12

  slave2:
    image: redis
    container_name: redis-slave-2
    restart: always
    - subnet:
    command: redis-server --slaveof 11.11.11.11 6379 --port 6381  --requirepass test@dbuser2020 --masterauth test@dbuser2020  --appendonly yes
    ports:
      - 6381:6381
    volumes:
      - ./data:/data
    networks:
      hx_net:
        ipv4_address: 11.11.11.13

networks:
  hx_net:
    driver: bridge
    ipam:
      config:
      - subnet: 11.11.11.0/16