version: '3.7'
services:
  master:
    image: redis
    container_name: redis-master
    restart: always
    command: redis-server --port 6379 --requirepass test@dbuser2020  --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data:/data

  slave1:
    image: redis
    container_name: redis-slave-1
    restart: always
    command: redis-server --slaveof 127.0.0.1 6379 --port 6380  --requirepass test@dbuser2020 --masterauth test@dbuser2020  --appendonly yes
    ports:
      - 6380:6380
    volumes:
      - ./data:/data


  slave2:
    image: redis
    container_name: redis-slave-2
    restart: always
    command: redis-server --slaveof 127.0.0.1 6379 --port 6381  --requirepass test@dbuser2020 --masterauth test@dbuser2020  --appendonly yes
    ports:
      - 6381:6381
    volumes:
      - ./data:/data
