version: '2.4'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
        ports:
            - "9200:9200"
        environment:
            discovery.type: single-node
            http.cors.enabled: "true"
            http.cors.allow-origin: "*"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata:/usr/share/elasticsearch/data
        mem_limit: 2048m
        mem_reservation: 1024m
    kibana:
        image: docker.elastic.co/kibana/kibana-oss:6.2.4
        ports:
            - "5601:5601"
    es-head:
        image: mobz/elasticsearch-head:5
        ports:
            - "9100:9100"
#        volumes:
volumes:
    esdata: